### ISSUE TITLE
Failed to generate voting results after /skip Status: success

### ISSUE THREAD

**Issue by rondevous** [c0re100/RadioBot#3]
https://user-images.githubusercontent.com/67483423/110191433-541a6000-7e20-11eb-8166-aeacbf7c510f.mp4

After song is skipped, the "vote" message fails to generate voting results.
Here's the final message:
```
Skip a song?
Vote count: 0
Vote Ended!

Status: Failed
```

**Group Participants:**
1 admin, 1 RadioBot

**Config**
```
"vote": {
  "enable": true,
  "vote_time": 15,
  "update_time": 15,
  "release_time": 30,
  "percent_of_success": 40,
  "participants_only": false,
  "user_must_join": false
}
```

**Comment by c0re100** [comment]
Strange.......
Why `Vote count: 0` happen lol
It should append vote starter into vote list first.....
and I can't reproduce :(
