### ISSUE TITLE
[suggestion] Make admin commands less global

### ISSUE THREAD

**Issue by rondevous** [c0re100/RadioBot#4]
(Admin) /play, /pause, /stop, /random

These commands are way too global. They work from any groupchat where the radiobot is in, even if that group is not used to play songs.

#Suggestion: Restrict the admin commands to work only in bot private chat and the group chat set in the config.

**Comment by rondevous** [comment]
Maybe allow the bot owner to /reload config in bot's private chat. (bot owner is the one who has deployed the bot). "bot_owner_id" = userid?

And to allow group's admin to control bot from private bot chat, the group admins' ID should be stored and updated by bot maybe?

**Comment by c0re100** [comment]
> Maybe allow the bot owner to /reload config in bot's private chat. (bot owner is the one who has deployed the bot). "bot_owner_id" = userid?
> 
> And to allow group's admin to control bot from private bot chat, the group admins' ID should be stored and updated by bot maybe?

`/reload` is remove soon, since it is a temporary command.
I want to implement bot config update via private chat at the beginning. 
Also allow group admins change some settings.
But there are many setting, so I need more time to think the design.
